### PR TITLE
+ added docker image with supervisord

### PR DESCRIPTION
**Pull request by Surt**
The pulll request contains a folder `docker` with the most simple files to start nlpserver on a docker container.
It follows the `laravel forge` instructions and uses the official python:3.8.5-slim-buster base image.

I did not included the image since I think it's more transparent to build it yourself.  Also, the language models are hardcoded.

# NLP Server Docker image

## Image creation

Inside the docker folder run 
```
 docker build . --tag nlpserver:1.0

 docker run --publish 6400:6400 --detach --name nlpserver nlpserver:1.0  

```
For CoreNLP on another container run:
```
docker run -p 9000:9000 nlpbox/corenlp
```

### CODE REVIEW

**Comment by flythenimbus** [comment]
Good stuff dude, I was looking for this! I'll give it a try and submit a review here.

**Comment by web64** [comment]
Thank you for submitting this PR!
I haven't had the chance to test this yet, so if @dugajean can test this and if it works ok I'm happy to merge this in.

**Comment by flythenimbus** [comment]
It fails here with an error:

```
polyglot download LANG:es
```

When removing this line and the next one the build passes. I'll keep testing.

**Comment by Surt** [comment]
> It fails here with an error:
> 
> ```
> polyglot download LANG:es
> ```
> 
> When removing this line and the next one the build passes. I'll keep testing.

yes I lack the skill to make it cofigurable in some way so I add them in the build. Probaby there is better methods like using a custom docker .env etc

**Comment by pankajthekush** [comment]
I have created the docker Image,docker file and docker compose file , download these two files from [this](https://github.com/pankajthekush/bots-docker/tree/master/nlpserver) folder and run `docker-compose up -d` it will be up and running in a jiffy, supports only English langue for now but you don't have to worry about the dependency.

Edit: In the docker file please enter the main repo git link , I have put mine because I wanted to use the server suited for live run
in Dockerfile
`instead of his RUN git clone https://github.com/pankajthekush/nlpserver.git`
you can  do
`RUN git clone https://github.com/web64/nlpserver.git`

If you don't make any changes it will still work.

**Comment by Surt** [comment]
Now it contains only EN. In any case anyone can edit the dockerfile to add more languages.

**Comment by web64** [comment]
Thank you guys for your contribution!
We should try to find a way to make it easy to configure additional languages.
One of the goals of the NLP Server is to have multilingual support. For now, editing the dockerfile should be ok.

Cheers,
Olav

**Pull request merged**
